### ISSUE TITLE
How can I change locale runtime?

### ISSUE THREAD

**Issue by himelnagrana** [urish/angular-moment#126]
Hi,
I can load specific locale using ````amMoment.changeLocale('nb');```` in my ````run()````. But if I need to change the locale runtime [``for example on a button click``] - what will be the suggested way?

Thanks.

**Comment by elimydlarz** [comment]
I would also like to know this. We're not having any luck with changeLocale inside our unit tests.

**Comment by armyofda12mnkeys** [comment]
+1. I have an app thats an international questionnaire. So the locale can change dynamically based on which questionnaire you get. I need to set this in the controller I believe since they can also change the language-country via a dropdown. Also I cannot just load <script src="components/moment/locale/de.js"></script> in my index.html manually since that locale could change dynamically.

**Comment by PeterDev1** [comment]
TEST

**Comment by fcristel** [comment]
+1

**Comment by urish** [comment]
`amMoment.changeLocale();` should do the trick. If you are calling it from your testing code, make sure you invoke angular's $digest() after changing the locale.

**Comment by fcristel** [comment]
worked, thanks! turns out that I was importing moment.js twice.
