### ISSUE TITLE
Dynamically update calendar dates 

### ISSUE THREAD

**Issue by audsKu** [urish/angular-moment#169]
The Timeago directive dynamically updates the relative timestamps if seconds or minutes have elapsed.

But the amCalendar filter does not update if a day has elapsed. For example, if the amCalendar output "Today at 10:33am", one day later, the same output should be updated to "Yesterday at 10:33am".

**Comment by urish** [comment]
In Anuglar 1.x, filters can't automatically update their output. That's why I initially created `amTimeAgo` as a directive and not as a filter.

 However, you can probably fix this by manually invoking a digest cycle every minute or so, add the following line to your applciation code:

`$interval(angular.identity, 60 * 1000); `

**Comment by audsKu** [comment]
Okay thank you!
