### ISSUE TITLE
Is there a way to show date instead of x days ago when past week ?

### ISSUE THREAD

**Issue by txRR** [urish/angular-moment#75]
Hello, first of all congratulations on your work, it's awesome !
I was wondering how I could manage to show a formated date instead of the "x days ago" if for example the date is past 7 days ?
Thank you

**Comment by sabrehagen** [comment]
+1

**Comment by matthewmeehan** [comment]
+1

**Comment by followtheart** [comment]
+1

**Comment by kat-scherr** [comment]
+1

**Comment by urish** [comment]
Seems like this was implemented by #93. I am looking for a better name for the configuration option - any ideas?

**Comment by btmdave** [comment]
Is this already available?

**Comment by urish** [comment]
@btmdave somebody sent a pr for this (#93). It has not been integrated into the code yet, as tests need to be written for it. Also, I am looking for a good name for the attribute that controls this. If you have any ideas, please share...

**Comment by followtheart** [comment]
>  angularMomentConfig --->  amConfig
> am-time-ago ---->                am-to-now

**Comment by slavafomin** [comment]
+1 for this feature. You could call such a parameter e.g. `fullDateShowTreshold`.

**Comment by urish** [comment]
@slavafomin very good, `fullDateThreshold` and `fullDateFormat` make good names in my opinion. 

If anybody can come up with something better, please let me know. Otherwise, we will stick with these.

**Comment by urish** [comment]
Implemented in [7ba16ce](https://github.com/urish/angular-moment/commit/7ba16ce7bac7b7bd10c24507d81982632a54c2ff).

Usage example:

    <span am-time-ago="message.time" am-full-date-threshold="7"></span>

Will display `message.time` as relative time if it is within the last 7 days, otherwise it will be displayed as a full date/time. You can also use the `am-full-date-format` attribute to control the format of the displayed date, and use `amTimeagoConfig` to set default values for those attributes.

Please let me know if there are any issues with the implementation. Otherwise, it will be released in a few days as part of angular-moment 0.10.

**Comment by RavenHursT** [comment]
@urish , has this been included in a release yet?  Would love to start using it in some places...

**Comment by urish** [comment]
Yes @RavenHursT, it is included in 0.10.0, as you can this in the [changelog](https://github.com/urish/angular-moment/blob/master/CHANGELOG.md)

**Comment by RavenHursT** [comment]
Thanks @urish
